### ISSUE TITLE
Specials not excluded from season

### ISSUE THREAD

**Issue by papaj-na-wrotkach** [ShokoAnime/Shokofin#37]
I have customized this option:
![image](https://user-images.githubusercontent.com/29522138/215268643-30c09995-afd7-481a-a8f1-20aaa117823f.png)

And despite choosing this option (before creating a library) the specials show up in season:
![image](https://user-images.githubusercontent.com/29522138/215268890-6814ade2-3fcc-4c5b-b8ef-b817b742a206.png)

The specials also show up in additional season (there are 12 regular episodes and 6 specials in main season and the same 6 specials in `Specials` season):
![image](https://user-images.githubusercontent.com/29522138/215269036-a804c14f-9b39-4141-8436-e87f51196ac6.png)

A interesting fact: despite being in `Specials` season...
![image](https://user-images.githubusercontent.com/29522138/215269351-a5d1d62d-1923-4b21-b4ba-2391d7acd427.png)

the first episode
![image](https://user-images.githubusercontent.com/29522138/215269322-296da1ee-45fd-4ee2-b513-a3f0cffad3ff.png)

**Comment by papaj-na-wrotkach** [comment]
By the way, when I change `Season number` of a special episode it doesn't show up in main season anymore - only in `Specials` as `Special - [title]` (before the change it was like the others - `1. [title]`):
![image](https://user-images.githubusercontent.com/29522138/215269915-0702efeb-0057-44ee-9a46-87e91bfb936c.png)

The changes are temporary though - they disappear after every metadata rescan.

**Comment by revam** [comment]
There was some error in the logic for when to use the assumed season number and when to use season zero. It should be fixed in https://github.com/ShokoAnime/Shokofin/commit/dad26e9848ca055d41e77744d1287677508541b3 and broadly available in the next stable release (No ETA). If you want the fix now then I will recommend using the unstable manifest, but that requires a recent daily version of Shoko Server to work at the moment, since it uses some new endpoints not available in the stable version yet.
