### ISSUE TITLE
Shokofin or ShokoJellyfin Manual install?

### ISSUE THREAD

**Issue by grravity** [ShokoAnime/Shokofin#8]
Due to ongoing issues with installing plugins in Jellyfin on Windows, sometimes it doesn't want to install.
I am attempting to install Shokofin manually. My question is, the install guide does not seem to be accurate?

It is stated `Extract the contained Shokofin.dll and meta.json, place both the files in a folder named Shokofin`
However, the latest release has the .dll as `ShokoJellyfin.dll` not `Shokofin.dll`. Inside the `meta.json` as well, it states `  "name": "ShokoJellyfin",`. This makes me question, the proper name of the .dll, as well as the folder name for the plugin.

From the looks of things, you guys are in the process of migrating from `ShokoJellyfin` to `Shokofin`, however it does not seem to be done yet.
So I wanted to ensure, as of the time of writing this (`Release v1.2.0`) the proper format should in fact be which of the following?:  

`/jellyfin/plugins/ShokoJellyfin/ShokoJellyfin.dll, meta.json`
`/jellyfin/plugins/ShokoJellyfin/Shokofin.dll, meta.json`
`/jellyfin/plugins/Shokofin/ShokoJellyfin.dll, meta.json`
 `/jellyfin/plugins/Shokofin/Shokofin.dll`

I assume `/jellyfin/plugins/ShokoJellyfin/ShokoJellyfin.dll, meta.json` to be the proper format?
I ask this because I have tested all of these, and restarted Jellyfin-server between each, and have not seen it appear in plugins. However again, there is a bug on Windows with plugins, and I have had a bit of a buggy experience with manually installing plugins as well. It may need some time to update or fix itself. Unless something is wrong with the plugin, or simply the naming format which is what I wanted to ensure above.
Thanks.

**Comment by revam** [comment]
@grravity There is currently no version of Shokofin (or ShokoJellyfin) compatible with the latest stable version of Jellyfin (`v10.6.0` as of writing this), since this plugin depends on changes made to Jellyfin that is set for the next minor/mayor release.

If you want to test the plugin, you can switch to an unstable release of Jellyfin and try again, adding the `.dll` file under `../plugins/<name>/<name>.dll`. The `1.2.0` release targets `10.7.0` (unstable) of Jellyfin.

Note: if you use Docker to run Jellyfin, then I'd recommend you use `jellyfin/jellyfin:20200903.2-unstable` as the container image, for the best compatibility.

**Comment by grravity** [comment]
>There is currently no version of Shokofin (or ShokoJellyfin) compatible with the latest stable version of Jellyfin (v10.6.0 as of writing this)

Ah, ok I will wait. It's worth adding that note into the Readme. Thank you.

**Comment by harshithmohan** [comment]
The preferred way to install plugins would be adding a repo but that has some issues right now on JellyFin's side. That's why it wasn't added in the readme.

As for the name of the dll and the folder, as you said, we went through a name change and I forgot to update the release.
Should be fixed with the new one.

And yes, the plugin won't be loaded on jellyfin version<10.7.0. That's why you couldn't see it.
I'm closing this issue.
